name: Release

on:
  push:
    tags: ["*"]

jobs:
  lint:
    uses: ./.gitea/workflows/lint.yaml
    secrets: inherit
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # setup-go automatically cache go.mod and go.sum.
      # So we don't need use actions/cache to cache go dependencies.
      # more info: https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          token: ${{ secrets.GH_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN}}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
